#!/usr/bin/env ruby

=begin
This file is part of ebayshopping.

Nome-Programma is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Nome-Programma is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Nome-Programma.  If not, see <http://www.gnu.org/licenses/>.
=end

require 'pathname'
APP_PATH = File.join(Pathname.new(File.dirname(__FILE__)).realpath.to_s, "/")
$: << APP_PATH

require 'searchwrapper.rb'

AppID = "Dev009d5c-57c5-4c49-854b-d6a41365508"
AppID_Sandbox = "Dev00793b-c9f4-4930-9a45-1c9d897f958"
SandboxMode = true

def main(parArgs)
	if parArgs.empty? then
		$stderr.puts "Please enter a search term"
		return 2
	end

	searchString = parArgs.first.dup
	#Not sure it needs special treatment - if so add it in EbService
	searchString.untaint

	appID = (SandboxMode ? AppID_Sandbox : AppID)
	searcher = SearchWrapper.new(nil, appID, SandboxMode, false)

	#autoPay, country, globalId, isMultiVariationListing, itemId, listingInfo,
	#location, paymentMethod, primaryCategory, sellingStatus, shippingInfo,
	#title, topRatedListing, viewItemURL
	searcher.each_result(searchString) do |tableResult|
		puts "#{tableResult["internalItemNum"]} - #{tableResult["title"]}"
	end
	return 0
end

exit(main(ARGV))
